/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package subsistem_parking;

import diceprox_main.MainForm;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows
 */
public class konfirmasiBookParkir extends javax.swing.JFrame {

    int selectedIndex;
    /**
     * Creates new form bookParkir2
     */
    public konfirmasiBookParkir() {
        initComponents();
        
        
//        refreshTable();
//        if (selectedIndex == 0) {
//            refreshTable(selectedIndex);
//        } else {
//            refreshTable(selectedIndex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jParkingTabel = new javax.swing.JTable();
        reservationID = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        LocationLabel = new javax.swing.JLabel();
        reservationDate = new javax.swing.JLabel();
        dateText = new javax.swing.JTextField();
        PoliceNumber = new javax.swing.JLabel();
        policeNumberText = new javax.swing.JTextField();
        ParkingLotCode = new javax.swing.JLabel();
        parkingLotCodeText = new javax.swing.JTextField();
        availableText = new javax.swing.JTextField();
        availableReservationLabel1 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        denahParkirArif = new javax.swing.JLabel();
        denahParkirMayjen = new javax.swing.JLabel();
        LocationText1 = new javax.swing.JTextField();
        eventLabel = new javax.swing.JLabel();
        bagian_kanan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBack.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(120, 125));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 70));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(120, 125));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 240, 200));

        jParkingTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ReservationID", "UserID", "ParkingLotID", "ReservationDate", "PoliceNumber", "ParkingLotCode"
            }
        ));
        jParkingTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jParkingTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jParkingTabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 550, 860, 370));

        reservationID.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        reservationID.setForeground(new java.awt.Color(57, 62, 70));
        reservationID.setText("ReservationID");
        getContentPane().add(reservationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 250, -1));

        idText.setBackground(new java.awt.Color(207, 219, 229));
        idText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        idText.setText("ID");
        idText.setEnabled(false);
        idText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTextFocusLost(evt);
            }
        });
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 500, 67));

        username.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        username.setForeground(new java.awt.Color(57, 62, 70));
        username.setText("Username");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 170, -1));

        nameText.setBackground(new java.awt.Color(207, 219, 229));
        nameText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nameText.setText("Username");
        nameText.setEnabled(false);
        nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFocusLost(evt);
            }
        });
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 500, 67));

        LocationLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LocationLabel.setForeground(new java.awt.Color(57, 62, 70));
        LocationLabel.setText("Location Name");
        getContentPane().add(LocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 250, -1));

        reservationDate.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        reservationDate.setForeground(new java.awt.Color(57, 62, 70));
        reservationDate.setText("Reservation Date");
        getContentPane().add(reservationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 290, -1));

        dateText.setBackground(new java.awt.Color(207, 219, 229));
        dateText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dateText.setText("Date");
        dateText.setEnabled(false);
        dateText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateTextFocusLost(evt);
            }
        });
        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });
        getContentPane().add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 500, 67));

        PoliceNumber.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PoliceNumber.setForeground(new java.awt.Color(57, 62, 70));
        PoliceNumber.setText("PoliceNumber");
        getContentPane().add(PoliceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, 230, -1));

        policeNumberText.setBackground(new java.awt.Color(207, 219, 229));
        policeNumberText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        policeNumberText.setText("Police Number");
        policeNumberText.setEnabled(false);
        policeNumberText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                policeNumberTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                policeNumberTextFocusLost(evt);
            }
        });
        getContentPane().add(policeNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 500, 67));

        ParkingLotCode.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ParkingLotCode.setForeground(new java.awt.Color(57, 62, 70));
        ParkingLotCode.setText("Parking Lot Code");
        getContentPane().add(ParkingLotCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 760, 280, -1));

        parkingLotCodeText.setBackground(new java.awt.Color(207, 219, 229));
        parkingLotCodeText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        parkingLotCodeText.setText("ParkingLotCode");
        parkingLotCodeText.setEnabled(false);
        parkingLotCodeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                parkingLotCodeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                parkingLotCodeTextFocusLost(evt);
            }
        });
        getContentPane().add(parkingLotCodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 750, 500, 67));

        availableText.setBackground(new java.awt.Color(207, 219, 229));
        availableText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        availableText.setText("Available Tickets");
        availableText.setEnabled(false);
        availableText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                availableTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                availableTextFocusLost(evt);
            }
        });
        getContentPane().add(availableText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 850, 500, 67));

        availableReservationLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        availableReservationLabel1.setForeground(new java.awt.Color(57, 62, 70));
        availableReservationLabel1.setText("IsAvailable");
        getContentPane().add(availableReservationLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 860, 280, -1));

        ConfirmButton.setBackground(new java.awt.Color(187, 224, 253));
        ConfirmButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 970, 250, 60));

        denahParkirArif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ArifRahmanHakim4x2.jpg"))); // NOI18N
        getContentPane().add(denahParkirArif, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 40, 500, 450));

        denahParkirMayjen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MayjendSungkono3x3.jpg"))); // NOI18N
        getContentPane().add(denahParkirMayjen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 40, 500, 450));

        LocationText1.setBackground(new java.awt.Color(207, 219, 229));
        LocationText1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LocationText1.setText("Location Name");
        LocationText1.setEnabled(false);
        LocationText1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LocationText1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LocationText1FocusLost(evt);
            }
        });
        getContentPane().add(LocationText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 500, 67));

        eventLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        eventLabel.setForeground(new java.awt.Color(57, 62, 70));
        eventLabel.setText("CONFIRMATION RESERVATION");
        getContentPane().add(eventLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        bagian_kanan.setBackground(new java.awt.Color(187, 187, 187));
        bagian_kanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_main_kiri.png"))); // NOI18N
        getContentPane().add(bagian_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        MainForm windowPlane = new MainForm();

        if (windowPlane == null || !windowPlane.isVisible()) {
            windowPlane.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void jParkingTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jParkingTabelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) jParkingTabel.getModel();
        int SelectedRows = jParkingTabel.getSelectedRow();
        
        idText.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        nameText.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        dateText.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        policeNumberText.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        parkingLotCodeText.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        availableText.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
    }//GEN-LAST:event_jParkingTabelMouseClicked

    private void idTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFocusGained
        if (idText.getText().equals("ID")) {
            idText.setText("");
        }
    }//GEN-LAST:event_idTextFocusGained

    private void idTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFocusLost
        if (idText.getText().equals("")) {
            idText.setText("ID");
        }
    }//GEN-LAST:event_idTextFocusLost

    private void nameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusGained
        if (nameText.getText().equals("Name")) {
            nameText.setText("");
        }
    }//GEN-LAST:event_nameTextFocusGained

    private void nameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusLost
        if (nameText.getText().equals("")) {
            nameText.setText("Name");
        }
    }//GEN-LAST:event_nameTextFocusLost

    private void dateTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTextFocusGained
        if (dateText.getText().equals("ParkingLotID")) {
            dateText.setText("");
        }
    }//GEN-LAST:event_dateTextFocusGained

    private void dateTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTextFocusLost
        if (dateText.getText().equals("")) {
            dateText.setText("ParkingLotID");
        }
    }//GEN-LAST:event_dateTextFocusLost

    private void policeNumberTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_policeNumberTextFocusGained
        if (policeNumberText.getText().equals("Police Number")) {
            policeNumberText.setText("");
        }
    }//GEN-LAST:event_policeNumberTextFocusGained

    private void policeNumberTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_policeNumberTextFocusLost
        if (policeNumberText.getText().equals("")) {
            policeNumberText.setText("Police Number");
        }
    }//GEN-LAST:event_policeNumberTextFocusLost

    private void parkingLotCodeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parkingLotCodeTextFocusGained
        if (parkingLotCodeText.getText().equals("Location")) {
            parkingLotCodeText.setText("");
        }
    }//GEN-LAST:event_parkingLotCodeTextFocusGained

    private void parkingLotCodeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parkingLotCodeTextFocusLost
        if (parkingLotCodeText.getText().equals("")) {
            parkingLotCodeText.setText("Location");
        }
    }//GEN-LAST:event_parkingLotCodeTextFocusLost

    private void availableTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_availableTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_availableTextFocusGained

    private void availableTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_availableTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_availableTextFocusLost

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void LocationText1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LocationText1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationText1FocusGained

    private void LocationText1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LocationText1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationText1FocusLost

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextActionPerformed

    //RefreshTable masih belum muncul di form !!
    public void refreshTable(int selectedIndex) {
        DefaultTableModel model = (DefaultTableModel) jParkingTabel.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[6]; //total kolom tampil
        
        for (com.ticketing.services.ParkingReservations obj : selectAllReservationsType(selectedIndex+1)) {
            rowData[0] = obj.getReservationID();
            rowData[1] = obj.getUserID();
            rowData[2] = obj.getParkingLotID();
            rowData[3] = obj.getReservationDate();
            rowData[4] = obj.getPoliceNumber();
            rowData[5] = obj.getLocationID();
            model.addRow(rowData);
        }
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBookParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBookParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBookParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBookParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konfirmasiBookParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JTextField LocationText1;
    private javax.swing.JLabel ParkingLotCode;
    private javax.swing.JLabel PoliceNumber;
    private javax.swing.JLabel availableReservationLabel1;
    private javax.swing.JTextField availableText;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bagian_kanan;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel denahParkirArif;
    private javax.swing.JLabel denahParkirMayjen;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JTable jParkingTabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField parkingLotCodeText;
    private javax.swing.JTextField policeNumberText;
    private javax.swing.JLabel reservationDate;
    private javax.swing.JLabel reservationID;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<com.ticketing.services.ParkingReservations> selectAllReservationsType(int parkingLotID) {
        com.ticketing.services.TicketingServices_Service service = new com.ticketing.services.TicketingServices_Service();
        com.ticketing.services.TicketingServices port = service.getTicketingServicesPort();
        return port.selectAllReservationsType(parkingLotID);
    }

    
}
