/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diceprox_main;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;

/**
 *
 * @author fransxeagle
 */
public class LoadForm extends javax.swing.JFrame {

    progressBarClass p1;

    /**
     * Creates new form LoadForm
     */
    public LoadForm() {
        initComponents();

        p1 = new progressBarClass(progress);
        p1.start();

        //untuk center
        this.setLocationRelativeTo(null);
    }

    class progressBarClass extends Thread {

        JProgressBar pbar;

        progressBarClass(JProgressBar pbar) {
            pbar = progress;
        }

        public void run() {
            int min = 0;
            int max = 10;

            progress.setValue(0);
            progress.setMinimum(min);
            progress.setMaximum(max);

            for (int i = min; i < max; i++) {
                progress.setValue(i);

                try {
                    sleep(100);

                } catch (InterruptedException ex) {
                    Logger.getLogger(LoadForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginForm().setVisible(true);
                }
            });

            // Menutup LoadForm
            LoadForm.this.dispose();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pleaseWaitLabel = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        logo = new javax.swing.JLabel();
        background_kiri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(670, 450));
        setMinimumSize(new java.awt.Dimension(670, 450));
        setPreferredSize(new java.awt.Dimension(670, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pleaseWaitLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pleaseWaitLabel.setForeground(new java.awt.Color(57, 62, 70));
        pleaseWaitLabel.setText("Please Wait");
        getContentPane().add(pleaseWaitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 350, -1));
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 560, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(120, 125));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 240, 200));

        background_kiri.setBackground(new java.awt.Color(187, 187, 187));
        background_kiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_main_kiri.png"))); // NOI18N
        getContentPane().add(background_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadForm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_kiri;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pleaseWaitLabel;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
