/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diceprox_main;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */


public class PemesananForm extends javax.swing.JFrame {

    int selectedIndex = 0;
    int idUser = UserSession.getUserId();
    /**
     * Creates new form PemesananForm
     */
    public PemesananForm() {
        initComponents();

        //untuk center
        this.setLocationRelativeTo(null);

        // Maximize the frame
        setExtendedState(MainForm.MAXIMIZED_BOTH);

        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pemesananLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPemesananParkingTabel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPemesananTabel = new javax.swing.JTable();
        nameLabel = new javax.swing.JLabel();
        comboBoxLokasi = new javax.swing.JComboBox<>();
        bagian_kanan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pemesananLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pemesananLabel.setForeground(new java.awt.Color(57, 62, 70));
        pemesananLabel.setText("PEMESANAN");
        getContentPane().add(pemesananLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(120, 125));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 240, 200));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBack.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(120, 125));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, 70));

        jPemesananParkingTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ReservationID", "Username", "ParkingLotName", "ReservationDate", "PoliceNumber", "ParkingSlot", "ParkingType", "HargaParking"
            }
        ));
        jPemesananParkingTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPemesananParkingTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jPemesananParkingTabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 1730, 340));

        jPemesananTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ticket Code", "User", "Event", "Type Ticket", "Jumlah Tiket", "Harga Total", "Waktu Reservasi", "Status Claim"
            }
        ));
        jPemesananTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPemesananTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jPemesananTabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 1730, 420));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(57, 62, 70));
        nameLabel.setText("Pilih Reservation");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 280, -1));

        comboBoxLokasi.setBackground(new java.awt.Color(207, 219, 229));
        comboBoxLokasi.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        comboBoxLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Event", "Parking" }));
        comboBoxLokasi.setMinimumSize(new java.awt.Dimension(72, 20));
        comboBoxLokasi.setPreferredSize(new java.awt.Dimension(72, 20));
        comboBoxLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLokasiActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 320, 70));

        bagian_kanan.setBackground(new java.awt.Color(187, 187, 187));
        bagian_kanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_main_kiri.png"))); // NOI18N
        getContentPane().add(bagian_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 1920, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        MainForm windowPlane = new MainForm();

        if (windowPlane == null || !windowPlane.isVisible()) {
            windowPlane.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jPemesananTabel.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[8]; //total kolom tampil
        String userID = String.valueOf(UserSession.getUserId());

        for (com.ticketing.services.Tickets obj : selectAllTicketUser(userID)) {
            rowData[0] = obj.getTicketID();
            rowData[1] = obj.getUsername();
            rowData[2] = obj.getEventName();
            rowData[3] = obj.getTicketType();
            rowData[4] = obj.getJumlahTiket();
            rowData[5] = obj.getHargaTotal();
            rowData[6] = obj.getReservationDate();
            rowData[7] = obj.isIsClaimed();
            model.addRow(rowData);
        }
    }
    
    public void refreshTableParking() {
        DefaultTableModel model = (DefaultTableModel) jPemesananParkingTabel.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[8]; //total kolom tampil

        for (com.ticketing.services.ParkingReservations obj : selectAllReservationPemesanan(idUser)) {
            rowData[0] = obj.getReservationID();
            rowData[1] = obj.getUsername();
            rowData[2] = obj.getParkingLotName();
            rowData[3] = obj.getReservationDate();
            rowData[4] = obj.getPoliceNumber();
            rowData[5] = obj.getParkingSlot();
            rowData[6] = obj.getParkingType();
            rowData[7] = obj.getHargaParking();
            model.addRow(rowData);
        }
    }

    private void jPemesananParkingTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPemesananParkingTabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPemesananParkingTabelMouseClicked

    private void jPemesananTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPemesananTabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPemesananTabelMouseClicked

    private void comboBoxLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLokasiActionPerformed
        // TODO add your handling code here:
        selectedIndex = (int) comboBoxLokasi.getSelectedIndex();
        if(selectedIndex == 0) //Event
        {
            jPemesananParkingTabel.setVisible(false);
            jPemesananTabel.setVisible(true);
            refreshTable();
        }
        else { 
            jPemesananTabel.setVisible(false);
            jPemesananParkingTabel.setVisible(true);
            refreshTableParking();
        }
        
    }//GEN-LAST:event_comboBoxLokasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bagian_kanan;
    private javax.swing.JComboBox<String> comboBoxLokasi;
    private javax.swing.JTable jPemesananParkingTabel;
    private javax.swing.JTable jPemesananTabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pemesananLabel;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<com.ticketing.services.Tickets> selectAllTicketUser(java.lang.String arg0) {
        com.ticketing.services.TicketingServices_Service service = new com.ticketing.services.TicketingServices_Service();
        com.ticketing.services.TicketingServices port = service.getTicketingServicesPort();
        return port.selectAllTicketUser(arg0);
    }

    private static java.util.List<com.ticketing.services.ParkingReservations> selectAllReservationPemesanan(int userID) {
        com.ticketing.services.TicketingServices_Service service = new com.ticketing.services.TicketingServices_Service();
        com.ticketing.services.TicketingServices port = service.getTicketingServicesPort();
        return port.selectAllReservationPemesanan(userID);
    }
}
